### ISSUE TITLE
Goober needs exactly one space after the selector or parsing fails. 

### ISSUE THREAD

**Issue by mpkelly** [cristianbote/goober#134]
Hi,

I've just migrated one of my open-source projects to Goober from Styled Components and found what I think is a bug. It seems Goober expects exactly one space after the CSS selector and parsing fails if you use zero or more than one. 

```CSS
// Wont work - no space
.a{

}
// Wont work - two spaces
.b  {

}
````
I have created this [sandbox](https://codesandbox.io/s/confident-chandrasekhar-sm4rt?file=/src/index.tsx) with an example. 

I would also say that error messages could be improved. The above produces an error like "Cannot set property '.classname-after-problematic-css' of undefined" which isn't so easy to debug. 

I had used Goober originally on two of my open-source projects but switched to SC which has a more seasoned parser and better error messages. Now I know Goober has this requirement I can migrate my other project over but I still think it's better to relax the regex and try and improve error handling. Sorry I didn't send a pull request - I am busy trying to complete my own projects right now.  

Thanks for the cool library which will be my default from now on. 

Mike

**Comment by mpkelly** [comment]
Hi again, 

I've found a more serious issue where duplicate classes are not merged. 

```CSS

  // this whole block is ignored and only the second one survives
  .c {
     font-size:24px;
  }

  .c {
    color:red;
  }
```

I also discovered that multi-part selectors must be separated by a single space to work properly. 

```CSS

  // Wont work - two spaces
  .c  div {
     font-size:24px;
  }

  // works ok
  .c div {
     font-size:24px;
  }

```
