### ISSUE TITLE
Bad transform in `:where()`

### ISSUE THREAD

**Issue by mikestopcontinues** [cristianbote/goober#315]
Hey, it seems the second value in `:where(a, b)` is being transformed when it shouldn't be.

This input:
```css
&:where(.column, .row) { display: flex; }
```

Yields this output:
```css
.go2745754553:where(.column, .go2745754553 .row) { display: flex; }
```

As you'd expect, the bug also occurs for `:is(a, b)` and for any specifier after the first (`:where(a, /* all bad => */ b, c, d)`).
