### ISSUE TITLE
/* comments */ break media query rules is strange, varied ways

### ISSUE THREAD

**Issue by mikestopcontinues** [cristianbote/goober#335]
One thing I noticed is that media queries are broken by comments. Sometimes the media block braces are omitted. Sometimes the styled component className is appended to the results. Here's the output from the very last example above. As you can imagine, it has consequences for the rules that follow each of these things...

```css
  /* --------- input --------- */

@media (min-width: 18em) { --min-xxs: 1; } /* xxs */
@media (min-width: 27em) { --min-xs: 1; } /* xs */

  /* --------- output --------- */

@media (min-width: 18em){.go2210534866{--min-xxs:1;}}.go2210534866  @media (min-width: 27em){--min-xs:1;}.go2210534866
```

**Comment by cristianbote** [comment]
Took another look at this and this:
```jsx
css`
@media (min-width: 18em) { --min-xxs: 1; } /* xxs */
@media (min-width: 27em) { --min-xs: 1; } /* xs */
`;
```
returns this:
```css
 @media (min-width: 18em){.go1776472861{--min-xxs:1;}}@media (min-width: 27em){.go1776472861{--min-xs:1;}}
 ```

which I would say is the expected value to be generated, is it not?
