### ISSUE TITLE
@media-queries with preceding content (without newline) will render without brackets

### ISSUE THREAD

**Issue by monkeyphysics** [cristianbote/goober#375]
First of all, my usecase is somewhat unique, as some CSS is coming from a JSON file as a single string.

I've checked the CSS specs, but as far as I can see, [newlines and/or whitespace are optional](https://www.w3.org/TR/css-syntax-3/#token-diagrams).

For easier replication and testing I've set up this [codepen demo](https://codepen.io/monkeyphysics/pen/qBjQQbw?editors=1010).

- Input:
  ```css
  h1 { font-size: 1rem; } @media only screen and (min-width: 850px) { h1 { font-size: 2rem; } }
  ```
- Expected output:
  ```css
  h1 { font-size: 1rem; } @media only screen and (min-width: 850px) { h1 { font-size: 2rem; } }
  ```
- Actual output:
  ```css
  h1 { font-size: 1rem; } @media only screen and (min-width: 850px) h1 { font-size: 2rem; }
  ```

Notice the **omitted brackets**, which makes the CSS invalid and the media-query is not effective.

When I insert a newline, it will work as expected:
- Input:
  ```css
  h1 { font-size: 1rem;  }
  @media only screen and (min-width: 850px) { h1 { font-size: 2rem; } }
  ```
- Ouput:
  ```css
  h1 { font-size: 1rem; } @media only screen and (min-width: 850px) { h1 { font-size: 2rem; } }
  ```
