### ISSUE TITLE
css returning same hash for different properties.

### ISSUE THREAD

**Issue by pmkroeker** [cristianbote/goober#39]
It seems like every call to css is outputting the same hash.

```typescript
const tickLabel = css({
    'font-size': '1em',
    'cursor': 'default',
    'user-select': 'none',
    '>.tick>line': {
        'stroke-width': '1px',
        'stroke-opacity': 0.5,
        'shape-rendering': 'crispEdges',
    },
    '>path': {
        'stroke-width': '2px',
    },
});

const gridStyle = css({
    '>path': {
        stroke: 'none',
    },
    '>.tick>line': {
        'stroke-width': '1px',
        'stroke-opacity': 0.5,
    },
});
console.log(tickLabel, gridStyle);
```
outputs `g015475 g015475`

Could this be related to the caching update? Seemed to be working properly before that was added.

**Comment by pmkroeker** [comment]
The final css is:
```css
 .g015475{
font-size:1em;
cursor:default;
user-select:none;
}
.g015475>.tick>line{
stroke-width:1px;
stroke-opacity:0.5;
shape-rendering:crispEdges;
}
.g015475>path{
stroke-width:2px;
}
```
