### ISSUE TITLE
Unique components receive non-unique classnames

### ISSUE THREAD

**Issue by mindplay-dk** [cristianbote/goober#609]
I was trying out goober and quickly ran into problems with nested selectors - have a look here:

https://stackblitz.com/edit/vitejs-vite-zbyg2anw?file=src%2FApp.tsx

The letters should turn red, green, blue and yellow when hovering - instead, the red/green/blue hover states all turn blue.

It looks like this is due to colliding hashes:

![Image](https://github.com/user-attachments/assets/828d971f-bbf2-422a-b224-ba6babee0dee)

For this simple example, you can fix it by making sure the styles are non-unique, e.g.:

```js
const R = styled('div')`
  color: gray;
`;

const G = styled('div')`
  color: darkgray;
`;

const B = styled('div')`
  color: lightgray;
`;
```

If unique components don't get a unique hash, you can't override them individually, as I'm trying to do in this example.

To ensure that unique components get unique class-names, probably the component ID should figure into the hash?

e.g. a global component ID counter being used to assign a unique ID to every styled component, and then including that in the hash?

**Comment by mindplay-dk** [comment]
Huh, that might not be the reason at all. 😅

Looking at the compiled CSS stylesheet:

```css
.go4059959218 {
  color: gray;
}
.go1859850488 {
  color: hotpink;
}
.go1202408551 {
  font-size: 80px;
  font-weight: bold;
}
.go1202408551:hover .go4059959218 {
  color: blue;
}
.go1202408551:hover .go1859850488 {
  color: yellow;
}
```

is it trying to emulate CSS native nested child selectors for older browsers?

native support for nesting is only just over a year new, but perhaps that's not needed anymore?

or maybe ensuring uniqueness for unique components like I suggested is enough? it appears to solve it, so I'm not sure. here's a before/after with the uniqueness change for my example:

![Image](https://github.com/user-attachments/assets/31e2df93-7a70-42bb-af4e-7aedb0b3cafc)

it looks to me as though it's unwrapping nested rules? but the result doesn't currently work quite like natively nested CSS? nor like nested CSS in other CSS-in-JS frameworks, I think? certainly not like I'd expect anyway. 😊
